/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#131313',
        'surface': '#131313',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-bright': '#3a3939',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c2c6d4',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'primary': '#aac7ff',
        'primary-container': '#4f90f3',
        'on-primary': '#002f65',
        'on-primary-container': '#002958',
        'primary-fixed': '#d7e3ff',
        'primary-fixed-dim': '#aac7ff',
        'secondary': '#bcc7de',
        'secondary-container': '#3e495d',
        'on-secondary': '#263143',
        'on-secondary-container': '#aeb9d0',
        'tertiary': '#ffb77c',
        'tertiary-container': '#d67a17',
        'on-tertiary': '#4d2700',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'outline': '#8c919e',
        'outline-variant': '#424752',
        'inverse-surface': '#e5e2e1',
        'inverse-primary': '#005cb9',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'base': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
        'mono-code': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin-slow': 'spin 3s linear infinite',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      backdropBlur: {
        '3xl': '48px',
      },
    },
  },
  plugins: [],
}
