'use client'
import { motion } from 'framer-motion'
import Navbar from '@/components/shared/Navbar'
import HeroSection from '@/components/landing/HeroSection'
import InputScreen from '@/components/landing/InputScreen'

const fadeInUp = {
  hidden: { opacity: 0, y: 40 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.8, ease: [0.16, 1, 0.3, 1] } }
}
const stagger = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.1 } }
}

const AGENTS = [
  { name: 'Priya',   role: 'Product Manager',   desc: 'Translates ideas into actionable PRDs and coordinates the development lifecycle.',         icon: '🧠' },
  { name: 'Arjun',   role: 'Systems Architect',  desc: 'Designs scalable data models, API schemas, and selects optimal tech stacks.',             icon: '🏗️' },
  { name: 'Disha',   role: 'UI/UX Designer',     desc: 'Crafts responsive, accessible interfaces and generates component systems.',               icon: '🎨' },
  { name: 'Bharat',  role: 'Backend Engineer',   desc: 'Implements core business logic, database migrations, and REST/GraphQL APIs.',            icon: '⚙️' },
  { name: 'Farhan',  role: 'Frontend Engineer',  desc: 'Builds interactive client applications focusing on performance and state management.',   icon: '🖥️' },
  { name: 'Qadir',   role: 'QA Specialist',      desc: 'Writes unit, integration, and E2E tests ensuring zero-defect deployments.',              icon: '🔍' },
  { name: 'Shreya',  role: 'Security Auditor',   desc: 'Scans code for vulnerabilities, enforces IAM policies, and ensures compliance.',         icon: '🔐' },
  { name: 'Dev',     role: 'DevOps Engineer',    desc: 'Configures CI/CD pipelines, container orchestration, and serverless deployments.',       icon: '📈' },
  { name: 'Ananya',  role: 'Data & Analytics',   desc: 'Integrates telemetry, defines KPIs, and sets up dashboards for user tracking.',          icon: '📊' },
]

const TERMINAL_LINES = [
  { text: '❯ npx create-navratna-company@latest',      color: '#4f90f3' },
  { text: 'Authenticating with Navratna Cloud... ✓',   color: '#c2c6d4' },
  { text: 'Initializing AI agent swarm (9/9 ready)...', color: '#c2c6d4' },
  { text: '✔ Product specs generated by Priya.',        color: '#aac7ff' },
  { text: '✔ DB Schema designed by Arjun.',             color: '#aac7ff' },
  { text: '✔ UI Mockups exported by Disha.',            color: '#aac7ff' },
]

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a]">
      {/* Cinematic background video */}
      <video autoPlay loop muted playsInline
        className="fixed top-0 left-0 min-w-full min-h-full z-[-2] object-cover opacity-40 pointer-events-none">
        <source src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260508_064122_c4750c0e-7476-4b44-94a2-a85a65c63bf2.mp4" type="video/mp4" />
      </video>
      <div className="fixed inset-0 z-[-1] pointer-events-none"
        style={{ background: 'radial-gradient(circle at center, rgba(10,10,10,0.6) 0%, #0a0a0a 100%)' }} />

      <Navbar />

      <main className="pt-32 pb-24 px-4 md:px-[48px] max-w-[1280px] mx-auto flex flex-col gap-24 relative z-10">

        {/* Hero */}
        <HeroSection />

        {/* Input */}
        <InputScreen />

        {/* Stats */}
        <motion.section
          initial="hidden" whileInView="visible" viewport={{ once: true }} variants={stagger}
          className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-4xl mx-auto w-full py-8 border-y border-white/5"
        >
          {[
            { value: '9',   label: 'Specialist Agents',  neon: false },
            { value: '~8m', label: 'To Functional MVP',  neon: false },
            { value: '$0',  label: 'Infrastructure Cost', neon: true },
          ].map((stat, i) => (
            <motion.div key={stat.label} variants={fadeInUp}
              className={`flex flex-col items-center text-center ${i > 0 ? 'border-t md:border-t-0 md:border-l border-white/5 pt-6 md:pt-0 md:pl-6' : ''}`}>
              <span className={`text-[48px] leading-[56px] font-bold ${stat.neon ? 'text-neon' : 'text-gradient'}`}>
                {stat.value}
              </span>
              <span className="text-[12px] tracking-[0.08em] font-semibold text-[#c2c6d4] mt-2 uppercase">{stat.label}</span>
            </motion.div>
          ))}
        </motion.section>

        {/* Agent Grid */}
        <motion.section
          id="agents"
          initial="hidden" whileInView="visible" viewport={{ once: true }} variants={stagger}
          className="max-w-5xl mx-auto w-full"
        >
          <motion.div variants={fadeInUp} className="flex items-center gap-4 mb-8">
            <h2 className="text-[32px] leading-[40px] font-bold text-[#e5e2e1]">The Navratna Nine</h2>
            <div className="h-px flex-grow bg-gradient-to-r from-white/10 to-transparent" />
          </motion.div>

          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            {AGENTS.map((agent, i) => (
              <motion.div key={i} variants={fadeInUp} className="liquid-glass rounded-xl p-6 agent-card">
                <div className="relative z-10 flex flex-col gap-4">
                  <div className="flex justify-between items-start">
                    <div className="w-12 h-12 rounded-full bg-[#131313] flex items-center justify-center text-2xl border border-white/10 shadow-inner">
                      {agent.icon}
                    </div>
                    <span className="w-2 h-2 rounded-full bg-[#4f90f3] animate-pulse shadow-[0_0_5px_#4f90f3]" />
                  </div>
                  <div>
                    <h3 className="text-[20px] leading-[28px] font-bold text-[#e5e2e1]">{agent.name}</h3>
                    <p className="text-[14px] text-[#4f90f3] mt-1">{agent.role}</p>
                  </div>
                  <p className="text-[14px] text-[#c2c6d4]/80 leading-[20px]">{agent.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* How it works */}
        <motion.section
          id="how-it-works"
          initial="hidden" whileInView="visible" viewport={{ once: true }} variants={stagger}
          className="max-w-4xl mx-auto w-full"
        >
          <motion.div variants={fadeInUp} className="flex items-center gap-4 mb-8">
            <h2 className="text-[32px] leading-[40px] font-bold text-[#e5e2e1]">How It Works</h2>
            <div className="h-px flex-grow bg-gradient-to-r from-white/10 to-transparent" />
          </motion.div>
          <div className="grid md:grid-cols-3 gap-6">
            {[
              { step: '01', title: 'Describe your idea', desc: 'Type any app idea in plain English. Enable Solo Founder Mode for free-tools-only recommendations.', icon: 'edit' },
              { step: '02', title: 'Watch agents collaborate', desc: '9 specialist agents debate, vote, and build in real-time. Watch PRDs, code, and tests generate live.', icon: 'groups' },
              { step: '03', title: 'Ship your product', desc: 'Download complete codebase, copy social posts, share your build. You played Tech Lead.', icon: 'rocket_launch' },
            ].map((item) => (
              <motion.div key={item.step} variants={fadeInUp} className="liquid-glass rounded-xl p-6 relative overflow-hidden">
                <div className="absolute top-4 right-4 text-[48px] font-bold text-white/3 leading-none select-none">{item.step}</div>
                <span className="material-symbols-outlined text-[28px] text-[#4f90f3] mb-4 block">{item.icon}</span>
                <h3 className="text-[20px] font-semibold text-[#e5e2e1] mb-2">{item.title}</h3>
                <p className="text-[14px] text-[#c2c6d4]/70 leading-[20px]">{item.desc}</p>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* Terminal */}
        <motion.section
          initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fadeInUp}
          className="max-w-3xl mx-auto w-full"
        >
          <div className="bg-[#0e0e0e] border border-white/10 rounded-lg overflow-hidden font-mono text-[14px] text-[#c2c6d4] shadow-2xl relative scanlines">
            <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-white/20 to-transparent" />
            <div className="bg-[#2a2a2a] px-4 py-2 border-b border-white/5 flex items-center gap-2">
              <div className="flex gap-1.5">
                <div className="w-3 h-3 rounded-full bg-[#ff5f56]" />
                <div className="w-3 h-3 rounded-full bg-[#ffbd2e]" />
                <div className="w-3 h-3 rounded-full bg-[#27c93f]" />
              </div>
              <span className="ml-4 text-xs opacity-50">navratna-cli — zsh</span>
            </div>
            <div className="p-4 leading-relaxed relative z-10">
              {TERMINAL_LINES.map((line, i) => (
                <div key={i} style={{ color: line.color }} className={i > 0 ? 'mt-1' : ''}>
                  {line.text}
                </div>
              ))}
              <div className="flex gap-2 mt-2 items-center">
                <span className="inline-block w-2 h-4 bg-[#4f90f3] animate-pulse" />
                <span className="opacity-70">Writing backend services...</span>
              </div>
            </div>
          </div>
        </motion.section>
      </main>

      {/* Footer */}
      <footer className="bg-[#131313] w-full py-12 border-t border-white/5 relative z-10">
        <div className="flex flex-col md:flex-row justify-between items-center px-[48px] max-w-[1280px] mx-auto gap-6">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="material-symbols-outlined filled text-[#4f90f3] text-[20px]">token</span>
              <span className="font-bold text-[16px] text-[#aac7ff]">NavratnaDevs</span>
            </div>
            <p className="text-[12px] tracking-[0.08em] text-[#c2c6d4]/40">© 2025 NavratnaDevs. Built for OpenAI × Outskill Hackathon.</p>
          </div>
          <div className="flex gap-6">
            {['Twitter', 'GitHub', 'Discord', 'Status'].map(link => (
              <a key={link} href="#"
                className="text-[14px] text-[#c2c6d4]/50 hover:text-[#aac7ff] transition-colors">
                {link}
              </a>
            ))}
          </div>
        </div>
      </footer>
    </div>
  )
}
